### ISSUE TITLE
Exchange#publish is documented as needing an integer, but passing in an integer fails

### ISSUE THREAD

**Issue by ivoanjo** [ruby-amqp/march_hare#102]
See:
https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/exchange.rb#L60

and test case:
```ruby
require 'march_hare'

connection = MarchHare.connect(uri: 'amqp://localhost:5672')

channel = connection.create_channel

exchange = channel.topic('foo')

exchange.publish(
  'hello, world!',
  routing_key: 'helloworld',
  properties: {timestamp: Time.now.to_i},
)
```

which results in:

```
TypeError: could not coerce Fixnum to class java.util.Date
              build_properties_from at /home/knuckles/.rvm/gems/jruby-9.1.5.0/gems/march_hare-2.18.0-java/lib/march_hare/metadata.rb:88
             block in basic_publish at /home/knuckles/.rvm/gems/jruby-9.1.5.0/gems/march_hare-2.18.0-java/lib/march_hare/channel.rb:607
  converting_rjc_exceptions_to_ruby at /home/knuckles/.rvm/gems/jruby-9.1.5.0/gems/march_hare-2.18.0-java/lib/march_hare/channel.rb:978
                      basic_publish at /home/knuckles/.rvm/gems/jruby-9.1.5.0/gems/march_hare-2.18.0-java/lib/march_hare/channel.rb:606
                            publish at /home/knuckles/.rvm/gems/jruby-9.1.5.0/gems/march_hare-2.18.0-java/lib/march_hare/exchange.rb:77
                             <main> at bug_report.rb:
```

I believe the fix here is to pass in something that can be coerced to `Date`, such as a `Time` instance (e.g. just `Time.now`, instead of `Time.now.to_i`).

**Comment by michaelklishin** [comment]
Instantiating a Ruby `Time` or a `java.util.Date` from an integer is not hard but such instances may or may not use the intended time zone. So should we support integers nonetheless or simply update the docs?

**Comment by ivoanjo** [comment]
To be honest, I'm a bit split. On one hand, bunny does use an integer (and I was porting some code over from bunny when I got bit). On the other hand, I do think passing in a `Time` object is much less error-prone, because, as you pointed out, it's harder to get bit by time zones.

I think passing in a `Time` is clearer, so I think this deviation is worth it :)

**Comment by michaelklishin** [comment]
@ivoanjo so then we should update the docs. Would you be interested in submitting a PR? :)

**Comment by ivoanjo** [comment]
I'm ok with that. I'll try to work on it today, if not, I'll have it up tomorrow or so.

**Comment by michaelklishin** [comment]
Sure. Thank you!
