### ISSUE TITLE
bundle update march_hare

### ISSUE THREAD

**Issue by pupca** [ruby-amqp/march_hare#106]
When I try to run `bundle install` I get this strange error :(

```
You have requested:
  march_hare ~> 2.18

The bundle currently has march_hare locked at 2.18.0.
Try running `bundle update march_hare`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
```

**Comment by michaelklishin** [comment]
This is a general Bundler question that has nothing to do with March Hare. I don't know what your intent here but Bundler installs dependencies from `Gemfile.lock`. You can delete it if you want to install the most recent versions of everything.

**Comment by pupca** [comment]
Hi! I don't think so. As removing the march_hare from Gemfile.lock will produce

```
Could not find gem 'march_hare (~> 2.18)' in any of the gem sources listed in
your Gemfile or available on this machine.
```

**Comment by michaelklishin** [comment]
@pupca I'm sorry but the only way I can think of for a gem to interfere with Bundler operations is if its `gemspec` fails to load entirely (and it is quite difficult to publish it to rubygems.org in the first place).

This is not a March Hare problem.

**Comment by michaelklishin** [comment]
Whoever you ask for help next, please do include your Gemfile and Gemfile.lock as it is really hard (or outright impossible) to tell what may be going on without those two.
