### ISSUE TITLE
Sometimes this library returns a ByteArrayLongString

### ISSUE THREAD

**Issue by andrewvc** [ruby-amqp/march_hare#109]
We've received reports from the field that sometimes this lib returns a `com.rabbitmq.client.impl.LongStringHelper$ByteArrayLongString`. A lot of JRuby code doesn't know how to handle this since it doesn't extend `String` or any other common object.

I think the correct thing to do is to convert this to a RubyString. @michaelklishin what do you think?

**Comment by michaelklishin** [comment]
Long strings are a protocol "feature" and they are used in property tables (e.g. optional message headers). Sometimes those values are never exposed to March Hare, in others it'd have to coerce arbitrarily nested arguments.

`ByteArrayLongString` can be [easily converted to a java.lang.String](https://github.com/rabbitmq/rabbitmq-java-client/blob/ebcadf6327073b00a716815ce5ebc5cfee536801/src/main/java/com/rabbitmq/client/impl/LongStringHelper.java#L83). If someone wants to submit a PR, I would consider it.

**Comment by andrewvc** [comment]
@michaelklishin I'd much prefer the patch be done here, and am glad to submit a PR for that. The tricky thing from a user perspective is that ruby users are not expecting that object necessarily (which is my case).

**Comment by michaelklishin** [comment]
@andrewvc feel free to look into it. Normalizing message headers should be enough for just about everyone.

**Comment by michaelklishin** [comment]
@andrewvc I agree that March Hare is the right place to address this. Just pointed out that it's easy to convert that "string-ish" object into a `java.lang.String`.
