### ISSUE TITLE
Can't install gem

### ISSUE THREAD

**Issue by c0mrade** [ruby-amqp/march_hare#114]
Hello I m unable to install this gem, even-though I have the source 'https://rubygems.org' at the top of my Gemfile, and I have this in my Gemfile:

```
gem 'march_hare', '~> 2.22'
```

Errored out:

Could not find gem 'march_hare (~> 2.22)' in any of the gem sources listed in
your Gemfile or available on this machine.

**Comment by michaelklishin** [comment]
I cannot reproduce:

```
λ ~/ rvm use jruby
λ ~/ gem install march_hare
Fetching: march_hare-2.22.0-java.gem (100%)
Successfully installed march_hare-2.22.0-java
1 gem installed
```

**Comment by michaelklishin** [comment]
March Hare is a JRuby-only library. Are you sure you are running JRuby? Switching to CRuby produces a "not found" from RubyGems:

```
λ ~/ rvm use 2.3
λ ~/ gem install march_hare
ERROR:  Could not find a valid gem 'march_hare' (>= 0) in any repository
```

**Comment by c0mrade** [comment]
hi @michaelklishin yes I m sure. Check this out :

```
ruby -v
jruby 1.7.19 (2.0.0p598) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +jit [darwin-x86_64]
```

I can also install it easily from console using `gem install`, I only observe the issue once it's inside my Gemfile. When I run into issue, I did find a workaround so I can explore your gem for potential production use, I clone repo locally and added this to my Gemfile :

```
gem 'march_hare', path: '~/workspace/march_hare'
```

Now works, I was able to install & connect to my broker

**Comment by michaelklishin** [comment]
I don't see that we indicate this in the gemspec but March Hare [only supports JRuby 9K](https://github.com/ruby-amqp/march_hare#supported-ruby-versions) these days.

**Comment by c0mrade** [comment]
thanks @michaelklishin I missed that bit. Very useful info.
