### ISSUE TITLE
Session#start should return self

### ISSUE THREAD

**Issue by larribas** [ruby-amqp/march_hare#116]
For better compatibility with bunny:

https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L278

**Comment by michaelklishin** [comment]
Feel free to submit a PR. As explained [in the comments](https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/session.rb#L316), `MarchHare::Session#start` is not necessary and only exists to avoid accidental delegation to the underlying Java client.
