### ISSUE TITLE
Do not hardcode NullTrustManager

### ISSUE THREAD

**Issue by andrewvc** [ruby-amqp/march_hare#127]
Originally reported here: https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/issues/44 by @sigsegv11 

Your thoughts @michaelklishin ?

> When setting the ssl_certificate_password/ssl_certificate_path for the rabbitmq plugin logstash keeps trusting certificates that can not be verified by the certificate provided in ssl_certificate_path.
This also higlighter by the continuous output of:

> 
> [WARN ][com.rabbitmq.client.NullTrustManager] This trust manager trusts every certificate, effectively disabling peer verification. This is convenient for local development but prone to man-in-the-middle attacks. Please see http://www.rabbitmq.com/ssl.html#validating-cerficates to learn more about peer certificate validation.
> 
> Diving a bit deeper into the code the issues seems to come from using march_hare without setting a custom truststore. ( see line 101). Because of this we fall back with the default "com.rabbitmq.client.NullTrustManager". It does trust everything by default without bothering checking certificates. As a result the ssl_certificate options simply doesn't work.

**Comment by michaelklishin** [comment]
`com.rabbitmq.client.NullTrustManager` and trust stores are orthogonal. Assuming "line 101" is [this one](https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/session.rb#L101), what March Hare doesn't do is allow for the user to pass a custom trust store manager. Sounds like a trivial fix.

**Comment by michaelklishin** [comment]
I'm not aware of an easy way of setting up key and trust stores from Ruby, so passing in a custom trust store manager is what should be done for now. What's the best way forLogstash to decide what implementation to use and how to set it up is a question I'm not really qualified to answer. Again, it comes down to a verbose Java API for that.

**Comment by jakelandis** [comment]
PR #128 submitted.  It changes the default to favor validation when cert path and pass is used, but still provides a means to opt out of validation.
