### ISSUE TITLE
When connecting using options other than :host and :port, error messages always refer to default host and port

### ISSUE THREAD

**Issue by robbavey** [ruby-amqp/march_hare#133]
When connecting to MarchHare, specifying host and port by means other than `:host`/`:port`, result in error messages referring to the default host and port, rather than those passed in.

For example, 

```
jruby-9.1.14.0 :018 > conn = MarchHare.connect(:addresses => ["invalid_host:999"])
```

Results in the following error:

```
MarchHare::ConnectionRefused: Connection to localhost:5672 refused: host unknown
```

Similarly, using 

```
jruby-9.1.14.0 :019 > conn = MarchHare.connect(:hosts => ["invalid_host"])
MarchHare::ConnectionRefused: Connection to localhost:5672 refused: host unknown
```
  
Specifying a working rabbitmq instance in those parameters results in a valid connection.

**Comment by psych0d0g** [comment]
nearing the issues birthday, ive just got bitten by it today and wasted around an hour on debugging, any plan to fix this?

**Comment by michaelklishin** [comment]
@psych0d0g this is open source software, so you are welcome to contribute. I do not make any ETA promises and unless an issue is critical, we get to them when we get to them.

**Comment by mikearruda** [comment]
> nearing the issues birthday, ive just got bitten by it today and wasted around an hour on debugging, any plan to fix this?

@psych0d0g As suggested by @jsvd in https://github.com/logstash-plugins/logstash-output-rabbitmq/issues/76#issuecomment-385366849, just remove the port option and pass the port in the host field like "host:port". I have confirmed this is working for me.

**Comment by michaelklishin** [comment]
`4.1.0` prints the entire effective list of addresses instead of default values.
