### ISSUE TITLE
Release 4.0

### ISSUE THREAD

**Issue by michaelklishin** [ruby-amqp/march_hare#143]
It's been a while that we had a new release and Logstash input/output could use https://github.com/ruby-amqp/march_hare/issues/141.

Per suggestion from @acogoluegnes we should wait for one more Java client release (scheduled to ship some time this week).

**Comment by michaelklishin** [comment]
@yaauie FYI.

**Comment by yaauie** [comment]
Are the changes breaking in any way? Is there a reason this can't be another minor in the 3.x series?

**Comment by michaelklishin** [comment]
The only breaking change is the JDK 8 baseline requirement. We try to bump versions when we adopt new major Java client versions, too.

**Comment by michaelklishin** [comment]
This is ready to go. I hope to produce a release in the next 24 hours.
