### ISSUE TITLE
Support for RabbitMQ 3.8.5

### ISSUE THREAD

**Issue by gopivalleru** [ruby-amqp/march_hare#150]
Does march_hare 3.0.0 support RabbitMQ 3.8.5 on jruby 9.2.8.0?

**Comment by michaelklishin** [comment]
Please use RabbitMQ mailing list for questions.

March Hare supports any RabbitMQ version starting with 2.0 (although some features and minor aspects of protocol behavior are obviously only available in 3.x, 3.7.x, 3.8.x and so on).

**Comment by gopivalleru** [comment]
@michaelklishin The is the March Hare mail list link http://rubymarchhare.info/articles/groups.google.com/group/ruby-amqp found on http://rubymarchhare.info/articles/community.html#mailing_list but its giving me 404.
