### ISSUE TITLE
Logging improvements in automatic recovery mode

### ISSUE THREAD

**Issue by deepakl** [ruby-amqp/march_hare#35]
march_hare version: 2.0.0.rc5

I was manually testing the automatic recovery process with march_hare. When the connection to the server is lost, march_hare does not log any messages to stdout so there is no visible clue that it is attempting recovery.

This caused me to spend sometime toggling different options to get automatic recovery working. After a bit, I realised that when the server came back up, march_hare would automatically reconnect.

It would be nice to see some log messages (similar to what `bunny` does) stating what march_hare is trying to do.

**Comment by michaelklishin** [comment]
The need for this was just highlighted in #107. I think we should consider copying what Bunny uses for logging. The only different part is that we can get exceptions that are Java objects.
