### ISSUE TITLE
Rely on Java client 3.4.1+ to perform connection recovery

### ISSUE THREAD

**Issue by andrewvc** [ruby-amqp/march_hare#64]
We've been experiencing some severe thread leaks with automatic recovery mode enabled. We see a large growth in threads + connections with automatic recovery enabled, up to the point where the number of threads OOMs the JVM.

We fixed this by forking the gem and calling cf.setAutomaticRecoveryEnabled(true) . 

This seems to do the same thing the ruby lib's auto recovery attempts to do, but with less bugs for us. I believe it was the case that the ruby recovery code was written to compensate for a the fact that older Java lib versions did not have setAutomaticRecoveryEnabled, but it seems that it would be preferable to delegate that work.

If you're open to accepting a patch we'd be glad to rip out the current auto recovery code and substitute setAutomaticRecoveryEnabled(true).

**Comment by michaelklishin** [comment]
We've recently fixed a binding recovery issue in the Java client, it will be in `3.4.4`. We should upgrade shortly after that release is out.

**Comment by andrewvc** [comment]
@michaelklishin Thanks for the update. Looking forward to it :)

**Comment by andrewvc** [comment]
@michaelklishin any updates on this ticket?

**Comment by michaelklishin** [comment]
I will cut a release tomorrow or so. Thanks for reminding.

**Comment by michaelklishin** [comment]
@andrewvc `2.10.0` is out. Note that I will release `2.11.0` which will depend on Java client `3.5.4` later this week. It has a memory leak plugged.

**Comment by andrewvc** [comment]
@michaelklishin awesome! :+1:
