### ISSUE TITLE
Consumer network/connection exception handling not working

### ISSUE THREAD

**Issue by gmudumbai** [ruby-amqp/march_hare#65]
Using jruby 1.7.12, march_hare 2.7.0 java

![capture](https://cloud.githubusercontent.com/assets/2583220/5065167/bfadb336-6de6-11e4-9c18-6fbd3f5bbe19.JPG)

This simple code seems to end when the connection goes down instead of handled by rescue column and retrying. I have used NetworkException, ChannelException, ConnectionLevelException. None seem to work. Mainly looking for NetworkException. Am I doing something wrong?
I am not using automatic recovery because I have multiple RMQ servers.

**Comment by michaelklishin** [comment]
Rescue blocks is not how connection recovery should be implemented. Please refer [to the docs](http://rubymarchhare.info/articles/error_handling.html). It is also a good idea to post code snippets instead of screenshots.
