### ISSUE TITLE
Bug in TLS detection

### ISSUE THREAD

**Issue by joshk** [ruby-amqp/march_hare#75]
```
NoMethodError: undefined method `tls_key_certificate_path_from' for MarchHare::Session:Class
                          connect at /app/vendor/bundle/jruby/1.9/gems/march_hare-2.8.0-java/lib/march_hare/session.rb:72
                          connect at /app/vendor/bundle/jruby/1.9/gems/march_hare-2.8.0-java/lib/march_hare.rb:20
```

https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/session.rb#L77

`tls_key_certificate_path_from` is an instance method but being called within a class method, thus it can't be found or used.

https://github.com/ruby-amqp/march_hare/commit/21532f4e108e5abe49a74ec9561a9d6ec7ab2d73

Due to this bug we are not able to use 2.8.

Also, thanks for the awesome lib :)

**Comment by michaelklishin** [comment]
Thank you for the detailed report!

I've pushed a quick attempt to fix that. Won't be able to verify for a few more hours.

**Comment by joshk** [comment]
Thanks for the awesome quick response!

And for your awesome hard work!

And for being awesome!

Awesome!

**Comment by michaelklishin** [comment]
@joshk `2.9.0` contains a proper fix with tests. Note that I've decided to [change TLS option names](https://github.com/ruby-amqp/march_hare/blob/master/ChangeLog.md#tls-connection-fixes) to be less confusing.

Thanks again for reporting.

**Comment by joshk** [comment]
Thank you @michaelklishin 

You rock!
