### ISSUE TITLE
Switch from HotBunny to MarchHare causing redelivery on queues

### ISSUE THREAD

**Issue by lardcanoe** [ruby-amqp/march_hare#79]
We upgraded from HotBunny 1.5 to the most recent March Hare in our JRuby 1.7.12 app. We noticed that on queues in the same rabbitmq instance that are only used by an MRI app, we get redeliveries. If we switch the JRuby app back to hot bunny, the redeliveries stop. We are using the same # of channels (1), same prefetch, etc... There is no noticeable change of cpu or other stats on the rabbitmq instance.

I'm looking for a little guidance on what to play around with to try to understand why march hare would have a negative impact on our server.

**Comment by michaelklishin** [comment]
Start by looking at RabbitMQ logs. Wireshark or Tracer (ships with the Java client) will tell what's going on on the wire.

Ruby clients have a [mailing list](http://groups.google.com/forum/#!forum/ruby-amqp).
