### ISSUE TITLE
Issue with Bundler 10: bundle package --all --path vendor/cache

### ISSUE THREAD

**Issue by DougEverly** [ruby-amqp/march_hare#81]
I’m getting this error in bundler 1.10. Does not happen in bundler 1.9. Not sure if its a bundler or march_hare issue. Other gems seem to package with no issues and this error is exclusive to march_hare.

# Error

```
You have requested:
  march_hare ~> 2.9.0

The bundle currently has march_hare locked at 2.9.0.
```

# Gemfile

```gem 'march_hare', '~> 2.9.0’```

# Gemfile.lock

```GEM
  remote: https://rubygems.org/
  specs:
    ...
    amq-protocol (1.9.2)
    march_hare (2.9.0-java)
    …
DEPENDENCIES
    …
  march_hare (~> 2.9.0)
    …

```

# Versions

```$ jruby -v
jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on OpenJDK 64-Bit Server VM 1.7.0_79-mockbuild_2015_05_14_07_23-b00 [linux-amd64]```

# Bundler 1.10 Error

```jruby -S bundle -v
Bundler version 1.10.5```

```
$ jruby -S bundle package --all --path vendor/cache
in version!
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
You have requested:
  march_hare ~> 2.9.0

The bundle currently has march_hare locked at 2.9.0.
Try running `bundle update march_hare`
```

# Bundler 1.9 OK

```$ jruby -S bundle -v
Bundler version 1.9.0```

```
jruby -S bundle package --all --path vendor/cache
  ...
Using march_hare 2.9.0
   …
Updating files in vendor/cache
Bundle complete! 13 Gemfile dependencies, 16 gems now installed.
Bundled gems are installed into ./vendor/cache.
Updating files in vendor/cache
```

**Comment by michaelklishin** [comment]
Seems to be a Bundler 10 issue to me.
