### ISSUE TITLE
Declaring a queue with a symbol name produces an esoteric error

### ISSUE THREAD

**Issue by cheald** [ruby-amqp/march_hare#82]
Something like `@channel.queue(:queue_name)` will produce an error like:

    Java::JavaLang::IllegalArgumentException: invalid value in table
      com.rabbitmq.client.impl.Frame.fieldValueSize(com/rabbitmq/client/impl/Frame.java:306)
      com.rabbitmq.client.impl.Frame.tableSize(com/rabbitmq/client/impl/Frame.java:246)
      com.rabbitmq.client.impl.ValueWriter.writeTable(com/rabbitmq/client/impl/ValueWriter.java:120)
      com.rabbitmq.client.impl.MethodArgumentWriter.writeTable(com/rabbitmq/client/impl/MethodArgumentWriter.java:139)
      com.rabbitmq.client.impl.AMQImpl$Queue$Declare.writeArgumentsTo(com/rabbitmq/client/impl/AMQImpl.java:1496)
      com.rabbitmq.client.impl.Method.toFrame(com/rabbitmq/client/impl/Method.java:83)
      com.rabbitmq.client.impl.AMQCommand.transmit(com/rabbitmq/client/impl/AMQCommand.java:102)
      com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(com/rabbitmq/client/impl/AMQChannel.java:316)
      com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(com/rabbitmq/client/impl/AMQChannel.java:298)
      com.rabbitmq.client.impl.AMQChannel.quiescingRpc(com/rabbitmq/client/impl/AMQChannel.java:233)
      com.rabbitmq.client.impl.AMQChannel.rpc(com/rabbitmq/client/impl/AMQChannel.java:224)
      com.rabbitmq.client.impl.AMQChannel.privateRpc(com/rabbitmq/client/impl/AMQChannel.java:209)
      com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(com/rabbitmq/client/impl/AMQChannel.java:118)
      com.rabbitmq.client.impl.ChannelN.queueDeclare(com/rabbitmq/client/impl/ChannelN.java:779)
      com.rabbitmq.client.impl.ChannelN.queueDeclare(com/rabbitmq/client/impl/ChannelN.java:61)
      java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:483)
      RUBY.block in queue_declare(/usr/local/rvm/gems/jruby-9.0.0.0/bundler/gems/march_hare-47788fee1585/lib/march_hare/channel.rb:489)
      org.jruby.RubyProc.call(org/jruby/RubyProc.java:308)
      usr.local.rvm.gems.jruby_minus_9_dot_0_dot_0_dot_0.bundler.gems.march_hare_minus_47788fee1585.lib.march_hare.channel.converting_rjc_exceptions_to_ruby(/usr/local/rvm/gems/jruby-9.0.0.0/bundler/gems/march_hare-47788fee1585/lib/march_hare/channel.rb:963)
      RUBY.queue_declare(/usr/local/rvm/gems/jruby-9.0.0.0/bundler/gems/march_hare-47788fee1585/lib/march_hare/channel.rb:488)
      RUBY.declare!(/usr/local/rvm/gems/jruby-9.0.0.0/bundler/gems/march_hare-47788fee1585/lib/march_hare/queue.rb:236)
      RUBY.block in queue(/usr/local/rvm/gems/jruby-9.0.0.0/bundler/gems/march_hare-47788fee1585/lib/march_hare/channel.rb:466)
      org.jruby.RubyKernel.tap(org/jruby/RubyKernel.java:1754)
      RUBY.queue(/usr/local/rvm/gems/jruby-9.0.0.0/bundler/gems/march_hare-47788fee1585/lib/march_hare/channel.rb:465)

It would be friendlier for march_hare should probably check for a string type before passing the value to the underlying Java driver, or to simply silently cast it to a string.

**Comment by michaelklishin** [comment]
Rejecting non-string names is a better idea. Feel free to look into it and submit a PR.
