### ISSUE TITLE
Channel is never recovered by automatic recovery

### ISSUE THREAD

**Issue by ginkel** [ruby-amqp/march_hare#83]
At the moment we are using March Hare v2.9.0. In order to debug a sporadic channel reconnection problem and check whether it may have been fixed in the current release, we upgraded to v2.11.0 and repeated our tests. Unfortunately, we noticed that channel recovery after a complete RabbitMQ cluster outage seems to be completely broken in v2.11.0.

Steps to reproduce:

1. Connect to a RabbitMQ cluster [1] with auto recovery enabled
2. Kill one of the RabbitMQ nodes: `killall -9 beam.smp`
3. March Hare will re-establish the channel by re-connecting and failing over to one of the remaining nodes
4. Kill all RabbitMQ nodes by issuing `killall -9 beam.smp` on all nodes. Wait some time and bring them back up.
5. Notice that the March Hare client will not recover its channel, but will infinitely raise `MarchHare::ChannelAlreadyClosed` on any attempt to use the client.

The recovery code itself does not log any exceptions once this happens.

We create the March Hare connection as follows:

    MarchHare.connect(..., network_recovery_interval: 0.1)

[1] We use a cluster with mirrored queues behind an AWS ELB

**Comment by michaelklishin** [comment]
There were no recovery changes between those versions.

**Comment by michaelklishin** [comment]
That network recovery interval is *very* low and leads to race condition between recovery attempts.

**Comment by ginkel** [comment]
I'm not exactly sure, but doesn't 2.11.0 use the recovery mechanism provided by the Java client instead of implementing that feature in Ruby?

**Comment by michaelklishin** [comment]
[No, it doesn't](https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/session.rb#L229-237). [The change log](https://github.com/ruby-amqp/march_hare/blob/master/ChangeLog.md) suggests the same.

Please bump your network recovery interval to a few seconds, as this very much seems like a race condition March Hare doesn't account for (intentionally).

**Comment by ginkel** [comment]
In that case, may I suggest to mention this race condition somewhere in the documentation? Reading the code left me with the impression that 100 ms would be feasible as even the specs use a recovery timeout of 200 ms.

If you don't mind, could you also please elaborate on the kind of race that you suspect is happening here?

**Comment by michaelklishin** [comment]
@ginkel March Hare does not synchronise recovery attempts. Doing so would make reasoning about recovery code significantly harder. Your network recovery interval should be roughly what it usually takes to recover. Otherwise there are all kinds of race conditions possible: from `MarchHare::Session` state changes to operations on the wire.

In addition, see RabbitMQ log files: automatic recovery works well most of the time but it cannot foresee and work around every possible edge case, so your channel may be closed because of a genuine channel exception.

I cannot suggest more without seeing your actual code. There were no recovery changes between those releases, so the sporadic issues are very likely due to a race condition somewhere and version changes are a red herring.

**Comment by michaelklishin** [comment]
As for the documentation, you [can always contribute improvements](https://github.com/ruby-amqp/rubymarchhare.info/blob/master/articles/error_handling.md).

**Comment by ginkel** [comment]
Noted. ;-)

Just one further question to rule out any misunderstandings on my end: What will March Hare do if the first recovery attempt fails (e.g., if the RabbitMQ cluster is still down after 5 s for whatever reason)? Will it try again?

From our tests 2.11.0 does not seem to do so even after reducing the probability of races by setting `network_recovery_interval` to 5. If I find some time I can try to bisect the issue as I am almost certain that 2.9.0 behaved differently. ;-) But maybe I'm just totally wrong...

**Comment by ginkel** [comment]
I did some further testing with `network_recovery_interval: 5` on both 2.9.0 and 2.11.0. For both version, I connected a March Hare client to a RabbitMQ cluster and gracefully shut down the RabbitMQ cluster (which caused March Hare to emit `ChannelAlreadyClosed` exceptions, which is expected). Then I waited for a couple of minutes and started the RabbitMQ cluster again. 2.9.0 will reliably recover the connection whereas 2.11.0 will remain in a disconnected state continuing to raise `ChannelAlreadyClosed` exceptions.

This looks like a major regression as one ends up with disconnected clients in case the RabbitMQ recovery takes longer than `network_recovery_interval`, which shouldn't be the regular case, but also cannot be ruled out. IMHO, continuing to increase `network_recovery_interval` is also no real solution as it will artificially lengthen short outages.

I see that there haven't been any relevant changes in `march_hare`, but maybe one of its dependencies caused the changed behavior.

If you have difficulties reproducing the issue please let me know how I can help.

**Comment by michaelklishin** [comment]
@ginkel there is only one dependency: the Java client, in which [nothing has changed in 3.5.3 and 3.5.4 w.r.t. recovery](rabbitmq.com/changelog.html). The only thing that did change was a checked exception added to some methods, but JRuby does not have checked exceptions and that's a compile time feature.

I've suggested looking at the logs instead of guessing. Do you see inbound connections? Any errors?

Our team is currently 2 people due to the holiday season. Connection recovery [has decent test coverage](https://github.com/ruby-amqp/march_hare/blob/master/spec/higher_level_api/integration/connection_recovery_spec.rb). Please dig deeper on your own.

**Comment by michaelklishin** [comment]
The following test does not reproduce your issue:

``` ruby
#!/usr/bin/env ruby

require 'march_hare'

conn = MarchHare.connect

conn

ch = conn.create_channel

puts "Connected"

loop do
  begin
    puts "Sleeping..."
    sleep 5.0

    ch.queue("march_hare.issue83")
  rescue MarchHare::ChannelAlreadyClosed => _
    sleep 4.0
    retry
  end
end
```

regardless of how long I shut RabbitMQ node down for: 3 seconds or 30.

Immediately after start I see an inbound connection:

```
=INFO REPORT==== 30-Jul-2015::16:31:07 ===
started TCP Listener on [::]:5672

=INFO REPORT==== 30-Jul-2015::16:31:07 ===
Management plugin started. Port: 15672

=INFO REPORT==== 30-Jul-2015::16:31:07 ===
Statistics database started.

=INFO REPORT==== 30-Jul-2015::16:31:07 ===
Server startup complete; 6 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * webmachine
 * mochiweb
 * rabbitmq_management_agent
 * amqp_client

=INFO REPORT==== 30-Jul-2015::16:31:10 ===
accepting AMQP connection <0.325.0> (127.0.0.1:50419 -> 127.0.0.1:5672)
```

**Comment by ginkel** [comment]
No problem, thanks for your help so far! I'll see what I can do and will let you know when have some further findings or maybe even a standalone test case.

**Comment by michaelklishin** [comment]
Neither does this more complicated example:

``` ruby
#!/usr/bin/env ruby

require 'march_hare'

conns = []
chs   = []
ary   = (0..100).to_a

10.times do |i|
  conn = MarchHare.connect
  conns << conn

  ary.sample.times do
    ch = conn.create_channel
    chs << ch
  end
end



puts "Connected"

loop do
  begin
    puts "Iteration..."
    sleep 1.0

    50.times do
      ch = chs.sample
      ch.queue("march_hare.issue83")
    end
  rescue MarchHare::ChannelAlreadyClosed => _
    sleep 1.0
    retry
  end
end
```

all connections recover as soon as RabbitMQ node is up:

```
=INFO REPORT==== 30-Jul-2015::16:39:32 ===
started TCP Listener on [::]:5672

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
Management plugin started. Port: 15672

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
Statistics database started.

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
Server startup complete; 6 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * webmachine
 * mochiweb
 * rabbitmq_management_agent
 * amqp_client

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.321.0> (127.0.0.1:50945 -> 127.0.0.1:5672)

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.324.0> (127.0.0.1:50946 -> 127.0.0.1:5672)

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.327.0> (127.0.0.1:50949 -> 127.0.0.1:5672)

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.330.0> (127.0.0.1:50947 -> 127.0.0.1:5672)

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.338.0> (127.0.0.1:50944 -> 127.0.0.1:5672)

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.360.0> (127.0.0.1:50948 -> 127.0.0.1:5672)

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.375.0> (127.0.0.1:50950 -> 127.0.0.1:5672)

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.378.0> (127.0.0.1:50951 -> 127.0.0.1:5672)

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.381.0> (127.0.0.1:50952 -> 127.0.0.1:5672)

=INFO REPORT==== 30-Jul-2015::16:39:32 ===
accepting AMQP connection <0.394.0> (127.0.0.1:50953 -> 127.0.0.1:5672)
```

So I highly suspect there is a channel exception somewhere during recovery.
