### ISSUE TITLE
Gem broken on linux systems (bad file perms)

### ISSUE THREAD

**Issue by andrewvc** [ruby-amqp/march_hare#88]
The packaged march_hare gem is fully broken due to bad perms in the packed gem.

```
andrewvc@andrewvc-elastic /tmp> ls -l march_hare-2.11.0-java/lib/ext/rabbitmq-client.jar
-rw-r-----  1 andrewvc  wheel  417376 Aug 26 15:13 march_hare-2.11.0-java/lib/ext/rabbitmq-client.jar
andrewvc@andrewvc-elastic /tmp> ls -l march_hare-2.11.0-java/lib/ext/commons-io.jar
-rw-r--r--  1 andrewvc  wheel  65621 Aug 26 15:13 march_hare-2.11.0-java/lib/ext/commons-io.jar
andrewvc@andrewvc-elastic /tmp>
```

On a multiuser unix (like linux) running as anything other than root can easily fail to load the rabbitmq-client.jar. 

We found this due to a user report here: https://github.com/elastic/logstash/issues/3781

**Comment by michaelklishin** [comment]
I don't have these permissions in my local repo. No idea what may have set them.

**Comment by andrewvc** [comment]
@michaelklishin it's a weird issue to be sure but I have verified it.

To repro this download the [latest rubygem](https://rubygems.org/downloads/march_hare-2.11.0-java.gem) and unpack it with `gem unpack`.

The perms even show on OSX, though if you're running as an admin it wont' matter

**Comment by andrewvc** [comment]
Maybe the perms got weird during packaging and then were later fixed?

**Comment by michaelklishin** [comment]
I've just built 2.12.0 which has the following permissions:

```
-rw-rw-r-- 1 antares antares  65K Aug 27 00:18 commons-io.jar
-rw-rw-r-- 1 antares antares 408K Aug 27 00:18 rabbitmq-client.jar
```

Downloaded .gem file permissions also seem correct. Since I always release from one of 2 machines, I wonder if this was a rubygems.org incident.

Give 2.12.0 a try.

**Comment by andrewvc** [comment]
Thanks @michaelklishin !

**Comment by michaelklishin** [comment]
@andrewvc yes but I have no idea what "packaging stage" that was. I release MH with a `gem build` followed by a `gem push`. No room to screw up :)

**Comment by andrewvc** [comment]
Probably just a stray cosmic ray :)
