### ISSUE TITLE
supplied consumer_tag not used for consumer

### ISSUE THREAD

**Issue by andreaseger** [ruby-amqp/march_hare#92]
According to the documentation it should be possible to set the consumer tag myself(obviously having to make sure myself that it's unique). If I do the following:

```
queue.subscribe(consumer_tag: "something uniq") do
  #...
end
```

The consumer tag will still be the auto generated one from march_hare.

If I read the code in https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/queue.rb#L183 correctly the consumer_tag option is actually never taken into account and not passed to the consumer.
Just 10 lines above in the documentation of subscribe is mentions the possibility to set the consumer tag ( https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/queue.rb#L173 )

Is this an oversight? Am I the only person who want's to set my own consumer_tags? For what it's worth bunny applies the consumer tag when supplied.

**Comment by michaelklishin** [comment]
Yes, it is not intentional. Many don't provide their own consumer tags and let either the client or RabbitMQ itself generate one. There is nothing wrong with providing you own, so please submit a pull request.

**Comment by michaelklishin** [comment]
@andreaseger thank you, I'll release `2.17` in the next day or so.

**Comment by andreaseger** [comment]
it's just a small thing but any update on when `2.17` will be released?

**Comment by michaelklishin** [comment]
It's out now.
