### ISSUE TITLE
Unable to find gem, 

### ISSUE THREAD

**Issue by fugufish** [ruby-amqp/march_hare#94]
Could not find gem 'march_hare (= 2.17.0)' in https://github.com/ruby-amqp/march_hare.git (at v2.17.0@b487b79).
Source contains 'march_hare' at: 2.17.0

The issue is strictly with bundler, I can manually 'gem install march_hare' but bundler vomits both trying to install from RubyGems and from github.

**Comment by michaelklishin** [comment]
I don't see what may be wrong as the version is what you expect in said commit.

Depending on a strict version with git makes little sense to me, even if you pin a commit. Just use the released version.

**Comment by fugufish** [comment]
I tried using the released version. Bundler says it can't find it on rubygems, however I can install it using gem install. It fails with bundler regardless if it done through Git or through using the released version.

**Comment by michaelklishin** [comment]
[The version is there](https://rubygems.org/gems/march_hare/versions/2.17.0-java). This project does not use GitHub issues for questions, so please take this to a mailing list (and more likely Bundler than ruby-amqp), with your Gemfile and Gemfile.lock files attached.
