### ISSUE TITLE
Session#disable_automatic_recovery broken due to typo

### ISSUE THREAD

**Issue by ivoanjo** [ruby-amqp/march_hare#95]
There is a typo in https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/session.rb#L241 where there is a missing `c` from the variable, thus if you try to use it:

```ruby
connection = MarchHare.connect(...)
connection.disable_automatic_recovery
/home/knuckles/.rvm/gems/jruby-9.1.5.0/gems/march_hare-2.18.0-java/lib/march_hare/session.rb:242: warning: instance variable @connetion not initialized
NoMethodError: undefined method `remove_shutdown_listener' for nil:NilClass
from /home/knuckles/.rvm/gems/jruby-9.1.5.0/gems/march_hare-2.18.0-java/lib/march_hare/session.rb:242:in `disable_automatic_recovery'
```

**Comment by michaelklishin** [comment]
That method is not a part of the public API, as a YARD tag indicates but thanks for spotting.

**Comment by ivoanjo** [comment]
Indeed, I just noticed it while I was reading through the source :)
Thanks for the quick fix.
